baseurl: /
title: Brantes
paginate: 5
theme: "hugo-PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Brantes
  description: "Blog para compartilhar artigos sobre meus estudos"
  keywords: [Blog, Portfolio, Docs, Study]
  author: Eu
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  mainSections:
    - posts
    - docs

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon-64x64.png"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  label:
    text: "Brantes"
    icon: /safari-pinned-tab.svg
    iconHeight: 30

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Olá! \U0001F44B"
    Content: Bem vindo ao meu blog

  socialIcons:
    #- name: x
    #  url: "https://x.com/"
    #- name: stackoverflow
    #  url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/pedrobrantes"
    - name: cv
      url: ".pdf"
    - name: linkedin
      url: "https://linkedin.com/in/brantes/"
    - name: email
      url: "mailto:"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/pedrobrantes/brantesblog/content"
    Text: "Sugerir Mudanças" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: Blogs
      url: /post/
      weight: 10
    - identifier: search
      name: Buscar
      url: /search/
      weight: 40
    - identifier: categories
      name: Categorias
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: docs
      name: Docs
      url: /docs/
      weight: 30
    #- identifier: github
    #  name: Github.com
    #  url: https://github.com/pedrobrantes
    #  weight: 30

pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
services:
  disqus:
    shortname: pedrobrantes